GET http://localhost:7071/api/GetWishlist
###
GET http://localhost:7071/api/AddMember?initials=MKUC
###
GET http://localhost:7071/api/GetMember?initials=ENHE
###
GET http://localhost:7071/api/UpdateMember?initials=ENHE&role=1
###
GET http://localhost:7071/api/GetAllMembers
###
### Test wishlist selection exists
GET http://localhost:7071/api/WishlistSelectionExists?initials=MKUC
### Get all wishlists
GET http://localhost:7071/api/GetWishlistSelections
###
GET http://localhost:7071/api/SyncWishlistAgainstBGG
###
GET http://localhost:7071/api/AddGame
###
GET http://localhost:7071/api/GetGame?gameId=112686
###
GET http://localhost:7071/api/DeleteGame
###
GET http://localhost:7071/api/DeleteMember
###
GET http://localhost:7071/api/DeleteMemberWishlist

### Add some sessions
GET http://localhost:7071/api/AddVotingSession?sessionId=1801820636
###
GET http://localhost:7071/api/GetVotingSessionEntries?votingSessionId=1801820636
###
GET http://localhost:7071/api/UpdateVotingSessionEntry?votingSessionId=1801820636
###
GET http://localhost:7071/api/ActivateVotingSession?sessionId=VotingSession_1
###
GET http://localhost:7071/api/GetAllVotingSessions
###
GET http://localhost:7071/api/GetVotingSession?sessionId=active
###
GET http://localhost:7071/api/GetAllGames
###
GET http://localhost:7071/api/GetAllAvailableGameStates