GET http://localhost:7071/api/GetWishlist
###
GET http://localhost:7071/api/GetMember?initials=MKUC
### missing user
GET http://localhost:7071/api/GetMember?initials=AAAAA
###
GET http://localhost:7071/api/AddMember?initials=MKUC
###
GET http://localhost:7071/api/GetAllMembers
###
GET https://bgg-api.azurewebsites.net/api/GetWishlist?code=4GcBaUuR/mQWefy9Lu9DBN2kLZ2Al2Ju4sasuwNho7aqWe3zchW5KQ==