GET http://localhost:7071/api/GetWishlist
###
GET http://localhost:7071/api/AddMember?initials=MKUC
###
GET http://localhost:7071/api/GetMember?initials=ENHE
###
GET http://localhost:7071/api/UpdateMember?initials=ENHE&role=1
###
GET http://localhost:7071/api/GetAllMembers
###
### Test wishlist selection exists
GET http://localhost:7071/api/WishlistSelectionExists?initials=MKUC
### Get all wishlists
GET http://localhost:7071/api/GetWishlistSelections
###
GET http://localhost:7071/api/SyncWishlistAgainstBGG
###
GET http://localhost:7071/api/AddGame
###
GET http://localhost:7071/api/GetGame?gameId=421
###
GET http://localhost:7071/api/DeleteGame
###
GET http://localhost:7071/api/DeleteMember
###
GET http://localhost:7071/api/DeleteMemberWishlist

### Add some sessions
GET http://localhost:7071/api/AddVotingSession?sessionId=24894979
###
GET http://localhost:7071/api/GetVotingSessionEntries?votingSessionId=24894979
###
GET http://localhost:7071/api/UpdateVotingSessionEntry?votingSessionId=24894979
###
GET http://localhost:7071/api/UpdateVotingSession?sessionId=1801820636&active=true
###
GET http://localhost:7071/api/GetVotingSession?sessionId=active